### GET a JWT Token for user DLEE
POST https://localhost:8443/restapi/jwt/ldapJsonLogin
Content-Type:application/json

{
  "username": "DLEE",
  "password":"Password2015"
}

### GET a JWT Token for user DAUSTIN
POST https://localhost:8443/restapi/jwt/ldapJsonLogin
Content-Type:application/json

{
  "username": "DAUSTIN",
  "password":"Password2015"
}